### Проверка сервера
GET http://localhost:8080

### Регистрация
POST http://localhost:8080/register
Content-Type: application/json

### Логин
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "user_7@kino.local",
  "password": "1234"
}