### Проверка сервера
GET http://localhost:8080

### Регистрация
POST http://localhost:8080/register
Content-Type: application/json

{
  "email": "admin_2@kino.local",
  "password": "1234"
}

### Логин (пароль админа_2 1234)
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "user_7@kino.local",
  "password": "1234"
}

### Создание фильма
POST http://localhost:8080/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNCwiZW1haWwiOiJ1c2VyXzdAa2luby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzY1NTY3OTAxfQ._3J9M_g3Wb_vnGKdTvEcgnkfF6z-tomQhPn716ZVNSc
Content-Type: application/json

{
    "title": "Lord of The Rings: Two Towers",
    "producer": "Barrie M. Osborne",
    "director": "Peter Jackson",
    "release_year": 2002
}

### Чтение
GET http://localhost:8080/movies

### Редактирование фильма
PUT http://localhost:8080/movies/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNCwiZW1haWwiOiJ1c2VyXzdAa2luby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzY1NTY3OTAxfQ._3J9M_g3Wb_vnGKdTvEcgnkfF6z-tomQhPn716ZVNSc
Content-Type: application/json

{
  "title": "Lord of The Rings: Brotherhood of the ring",
  "producer": "Barrie M. Osborne",
  "director": "Peter Jackson",
  "release_year": 2001
}


### Удалить фильм (ID = 2)
DELETE http://localhost:8080/movies/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNCwiZW1haWwiOiJ1c2VyXzdAa2luby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzY1NTY3OTAxfQ._3J9M_g3Wb_vnGKdTvEcgnkfF6z-tomQhPn716ZVNSc